# Generated by Django 4.2.28 on 2026-05-06 18:29

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('level_name', models.CharField(max_length=200)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('color_wheel', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
                ('color', models.CharField(blank=True, help_text='Comma-separated hex colors for gradient', max_length=500, null=True)),
                ('display_name', models.CharField(blank=True, editable=False, max_length=300, verbose_name='Display Name (with Roman if needed)')),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevelInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.FloatField(blank=True, help_text='Time taken (seconds) to complete the level', null=True)),
                ('stroke_count', models.IntegerField(blank=True, help_text='Number of keystrokes used during the attempt', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy percentage (0–100) submitted by the frontend', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('stars_earned', models.IntegerField(default=0, help_text='0=not completed, 1=completed, 2=+accuracy, 3=+accuracy & time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='api.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stars_earned', '-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='User_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_accuracy', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_keystrokes', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True, verbose_name='Set active?')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.level')),
            ],
            options={
                'verbose_name_plural': "User's Levels",
            },
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
